/*
 * Auto-generated by Frida. Please modify to match the signature of CCCryptorCreate.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */



{
  /**
   * Called synchronously when about to call CCCryptorCreate.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter(log, args, state) {
    const key_arr = new Uint8Array(ArrayBuffer.wrap(args[3], args[4].toInt32()));
    log(`CCCryptorCreate(op=${op2str(args[0])}, alg=${alg2str(args[1])}, options=${opts2str(args[2])}, key=${uint8array2hexstr(key_arr)}, keyLength=${args[4].toInt32()}, iv=${iv2str(args[5])}, cryptorRef=${args[6]})`);
  },

  /**
   * Called synchronously when about to return from CCCryptorCreate.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave(log, retval, state) {
  }
}
